export const AVAILABLE_PROMPTS = [
  "A boundary of mine is",
  "A daily essential",
  "A dream home must include",
  "A friend's review of me",
  "A life goal of mine",
  "A quick rant about",
  "A random fact I love is",
  "A shower thought I recently had",
  "All I ask is that you",
  "Apparently, my life's soundtrack is",
  "Ask me anything about",
  "Best travel story",
  "Biggest risk I've taken",
  "Can we talk about",
  "Change my mind about",
  "Choose our first date",
  "Cook with me",
  "Dating me is like",
  "Do you agree or disagree that …",
  "Don't hate me if I …",
  "First round is on me if …",
  "Give me travel tips for …",
  "Give me your honest opinion about …",
  "Green flags I look for",
  "Guess my secret talent",
  "Guess the song",
  "Hi from me and my pet",
  "How to pronounce my name",
  "I bet you can't …",
  "I feel most supported when …",
  "I geek out on …",
  "I get myself out of a funk by …",
  "I go crazy for …",
  "I hype myself up by …",
  "I know the best spot in town for …",
  "I recently discovered that …",
  "I want someone who …",
  "I wind down by …",
  "I wish more people knew …",
  "I won't shut up about …",
  "I'll brag about you to my friends if …",
  "I'll fall for you if …",
  "I'll give you the set-up, you guess the punchline",
  "I'll pick the topic if you start the conversation",
  "I'm a 10 but …",
  "I'm convinced that …",
  "I'm looking for …",
  "I'm weirdly attracted to …",
  "If loving this is wrong, I don't want to be right",
  "If we won the lottery, let's spend it on …",
  "Instead of grabbing drinks, let's …",
  "Let me teach you how to …",
  "Let's break the ice by …",
  "Let's chat about …",
  "Let's debate this topic",
  "Let's make sure we're on the same page about …",
  "Like for tips about …",
  "Most spontaneous thing I've done",
  "My BFF's take on why you should date me",
  "My Love Language is …",
  "My best Dad joke",
  "My best celebrity impression",
  "My biggest date fail",
  "My cry-in-the-car song is …",
  "My favorite line from a movie …",
  "My friends ask me for advice about …",
  "My greatest strength …",
  "My happy place …",
  "My last journal entry was about …",
  "My most controversial opinion is …",
  "My most irrational fear (is) …",
  "My review of …",
  "My self-care routine is …",
  "My simple pleasures …",
  "My therapist would say I …",
  "Never have I ever …",
  "One thing I'll never do again …",
  "Pick our first getaway",
  "Pick the best one",
  "Pick the most underrated",
  "Pick the one that's gotta go",
  "Proof I have musical talent",
  "Put a finger down if …",
  "Quick story time",
  "Rate my fit",
  "Saying \"Hi!\" in as many languages I know",
  "Something that's non-negotiable for me is …",
  "Something that's special to me …",
  "Teach me something about …",
  "The best spot in town for pizza is …",
  "The best way to ask me out is by …",
  "The dorkiest thing about me is …",
  "The hallmark of a good relationship is …",
  "The key to my heart is …",
  "The last time I cried happy tears was …",
  "The one thing I'd love to know about you is …",
  "The one thing you should know about me is …",
  "The way to win me over is …",
  "Therapy recently taught me …",
  "Things I own that just make sense …",
  "This year, I really want to …",
  "To me, relaxation is …",
  "Together, we could …",
  "Try to guess this about me …",
  "Two truths and a lie",
  "Typical Sunday",
  "Unusual skills …",
  "We'll get along if …",
  "We'll instantly hit it off if …",
  "We're the same type of weird if …",
  "Weirdest gift I have given or received …",
  "What I order for the table …",
  "What if I told you that …",
  "When I need advice, I go to …",
  "Which do we have in common?",
  "Which event should we time-travel to?",
  "Which is worth splurging on?",
  "Worst idea I've ever had",
  "Would you rather …",
  "You should leave a comment if …",
  "You should not go out with me if …"
] as const;

export type PromptType = typeof AVAILABLE_PROMPTS[number];